add functionality for mini-statement
achyuta116/SE pull request #7
Opened 2022-11-05 07:02 UTC by nkilm

### changes made
- Added new file `mini_statement.py` which displays 5 most recent transactions.
- Updated `requirements.txt`

2022-11-05 18:52 UTC, hita03 requested changes
There's a function for mini statement `customer_account_mini_statement()` in `account.py`. Please move it there

2022-11-06 06:07 UTC, achyuta116 reviewed
Please move the function to `accounts.py` as @hita03 stated.
Apart from that, if the code has been validated we should be fine to merge it into the main branch

2022-11-06 06:56 UTC, nkilm commented
@hita03 @achyuta116 Check

2022-11-06 10:03 UTC, hita03 approved these changes

2022-11-06 10:03 UTC, closed without merging