added balance, deposit, and withdraw to `account.py`,  init.py to mod…
achyuta116/SE pull request #9
Opened 2022-11-07 19:12 UTC by hita03

added balance, deposit, and withdraw to `account.py`,  init.py to modules, `accounts_test` in `tests`
todo - update(changes in account balance) and append(for ministatement) on `database.json`

2022-11-08 13:11 UTC, achyuta116 requested changes
Please remove the empty __init__.py file from utils. We only need atmsimulator and tests to be packages, revise imports accordingly since it might break changes already pushed to the main branch.

2022-11-08 13:11 UTC, achyuta116 commented on tests/account_tests.py
> +        globals.account={
`globals.account` within `globals.py` isn't an array of accounts, it's only the account object that is retrieved from the server. Fix your tests and functions within `account.py` accordingly. Apart from that, if the tests work as they're expected to should be all good.

2022-11-08 13:11 UTC, achyuta116 commented on tests/database.json
> +{
Replace the contents of this with the database.json file that has more accounts to play around with please. Remember to keep pulling from the main branch to see any changes.

2022-11-08 13:11 UTC, achyuta116 commented on atmsimulator/account.py
>  def customer_account_mini_statement():
I believe @nkilm had written an implementation of mini statement, did you check with him before you made changes?

2022-11-08 14:20 UTC, nkilm commented
@hita03 Please use `inquirer` wherever we are taking user input, also add basic verification. E.g, for withdrawl/deposit the input should only be float/int.

2022-11-10 14:15 UTC, hita03 commented
Got it.

2022-11-10 19:52 UTC, hita03 commented
* formatted `account.py`. `autopep8` installed for formatting code. It auto-installs other packages.`pip install -U autopep8` only.
* `__init__.py` was added to `utils` folder to modularise it. (for imports)
* `globals.account` in `tests/account_tests.py` has been updated to an object.
* `tests/database.json` was a replica of the actual database. It isn't used in tests as we're only hardcoding `globals.account`. So it's been deleted.
* addition to @nkilm's the mini-statement is a single `if-else` to check whether this service has been disabled, continuing only if it is enabled.
* cash limit of 2,50,000 rs has been included in account.py's `customer_account_cash_withdrawal`
*  fixed up `account.py` - inquirer for all inputs, verification.

2022-11-11 01:42 UTC, achyuta116 approved these changes

2022-11-11 01:50 UTC, merged